language: perl
install: true
script: perl ./Build.PL
perl:
  - "5.14"
  - "5.18"
  - "5.20"
branches:
  only:
    - master
    - stable
before_script:
    - sudo add-apt-repository ppa:boost-latest/ppa
    - sudo apt-get update -qq
    - sudo apt-get install libboost-thread1.55-dev libboost-system1.55-dev
